[project]
name = "aiogram_template"
version = "1.0.0"
description = "Aiogram template"
readme = "README.md"
license = "CC-BY-NC-ND-4.0"
license-files = ["LICENSE.md"]
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.21.0",
    "pydantic-settings>=2.10.1",
    "redis>=6.2.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "ruff>=0.12.2",
]
